version: '3.9'

services:
  RSA_web:
    image: docker.io/nginx:mainline-alpine3.18-slim
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - RSA_php-fpm
  RSA_php-fpm:
    image: docker.io/php:8.1.25RC1-fpm-alpine3.18
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
  RSA_composer:
    image: docker.io/composer:latest
    container_name: composer
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
  RSA_db:
    image: docker.io/mysql:latest
    container_name: db
    restart: unless-stopped
    ports: # Remove if in production
      - 3306:3306
    volumes:
      - RSA_db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  RSA_db:
